# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9844d5f20a05abd6cb77eca664884f3281e4e0c27cc491222137b3676b6bbf862159e9e64d903bdf71ad855dd949899b30082647c97131b734b1cedba95616d0

test:
  secret_key_base: 65a77d681741221cbfb4d19dbce66867251d330ecbf6bfc85c01b58e0a689f829f287c820b6517695a1c0241d4ff3a773718b230c6d628b629581a1feb7899ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
